modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/gisellevonbingen/Minecraft-MoreMekanismProcessing/issues"

[[mods]]
    modId="moremekanismprocessing"
    version="${file.jarVersion}"
    displayName="More Mekanism Processing"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-mekanism-processing"
    authors="gisellevonbingen"
    description='''Add mekanism's ore processing to other mod's ores'''

[[dependencies.moremekanismprocessing]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moremekanismprocessing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moremekanismprocessing]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.1.1,)"
    ordering="AFTER"
    side="BOTH"
